---
output:
  github_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.path = "figures/"
)
```

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)

con <- RPostgres::dbConnect(
  RPostgres::Postgres(),
  host =  Sys.getenv("HOST"),
  user = "shiny",
  password = Sys.getenv("SHINY_PSQL_PWD"),
  dbname = "shiny"
)

plot_data <- function(data){
  
  ggplot(data, aes(fecha_hora, n)) +
    geom_line(group = 1, size = 1.1, color = "gray60") +
    scale_x_date(
      date_labels = "%Y",
      breaks = "year",
      minor_breaks = "months",
      position = "top"
      ) +
    scale_y_continuous(
      # limits = c(0, NA),
      labels = scales::comma, position = "right"
      ) +
    theme_minimal() +
    labs(x = NULL, y = NULL)
  
}

data <- tbl(con, "estaciones_datos") |> 
  count(fecha_hora) |> 
  collect() |> 
  mutate(n = as.integer(n))

data_month <- data |> 
  mutate(fecha_hora = floor_date(fecha_hora, "month")) |> 
  count(fecha_hora, wt = n)

data_year <- data |> 
  mutate(fecha_hora = floor_date(fecha_hora, "year")) |> 
  count(fecha_hora, wt = n)
```

# ODES DB

Updated on `r Sys.time()`

--- 

## Daily summary

```{r}
data |> 
  filter(year(fecha_hora) >= 2021) |> 
  plot_data()
```

Count of last 2 week:

```{r, results='asis'}
data |> 
  arrange(fecha_hora) |> 
  tail(14) |> 
  mutate(n = scales::comma(n)) |> 
  arrange(desc(fecha_hora)) |> 
  knitr::kable(align = "lr")
```

## Monthly summary

```{r}
data_month |> 
  filter(year(fecha_hora) >= 2021) |> 
  plot_data() 
```

Count of last 12 months:

```{r, results='asis'}
data_month |> 
  arrange(fecha_hora) |> 
  tail(12) |> 
  mutate(n = scales::comma(n)) |> 
  arrange(desc(fecha_hora)) |> 
  knitr::kable(align = "lr")
```

## Yearly summary

```{r}
data_year |> 
  # filter(year(fecha_hora) >= 2010) |> 
  plot_data() +
  scale_x_date(
    date_labels = "%Y",
    breaks = "year",
    minor_breaks = NULL,
    position = "top",
    sec.axis = dup_axis()
    ) + 
  scale_y_continuous(
    labels = scales::comma, position = "right",
    sec.axis = dup_axis()
    ) 
```

Count of last 10 years:

```{r, results='asis'}
data_year |> 
  arrange(fecha_hora) |> 
  tail(10) |> 
  mutate(n = scales::comma(n)) |> 
  arrange(desc(fecha_hora)) |> 
  knitr::kable(align = "lr")
```
