on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
  - cron: 0 */6 * * *

name: updatedb

jobs:
  updatedb:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install agrometR
        shell: Rscript {0}
        run: |
          remotes::install_github("ODES-Chile/agrometR")

      - name: Create and populate .Renviron file
        env:
          HOST: ${{ secrets.HOST }}
          SHINY_PSQL_PWD: ${{ secrets.SHINY_PSQL_PWD }}
        run: |
          touch .Renviron
          echo SHINY_PSQL_PWD="$SHINY_PSQL_PWD" >> .Renviron
          echo HOST="$HOST" >> .Renviron

      - name: Update DB
        shell: Rscript {0}
        run: |
          source("R/updatedb.R", echo = TRUE)

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "updating readme.md" --author 'Joshua Kunst <jbkunst@gmail.com>'
          git push
