on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
  - cron: 0 5 * * *

name: updatedb

jobs:
  updateddbb:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install agrometR
        shell: Rscript {0}
        run: |
          remotes::install_github("ODES-Chile/agrometR")

      - name: Create and populate .Renviron file
        run: |
          echo SHINY_PSQL_PWD="MAPPED_SHINY_PSQL_PWD" >> ~/.Renviron
          echo HOST="MAPPED_HOST " >> ~/.Renviron

        shell: bash
        env:
          MAPPED_SHINY_PSQL_PWD: ${{ secrets.SHINY_PSQL_PWD }}
          MAPPED_HOST : ${{ secrets.HOST }}

      - name: Update DB
        shell: Rscript {0}
        run: |
          source("R/updatedb.R", echo = TRUE)

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "updating data and report" --author 'Joshua Kunst <jbkunst@gmail.com>'
          git push
